pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                echo 'Building...'
            }
        }
    }
}
